Make specific version from releases required in prod mode

diff --git a/bin/lib/run_from_docker b/bin/lib/run_from_docker
--- a/bin/lib/run_from_docker
+++ b/bin/lib/run_from_docker
@@ -15,6 +15,10 @@ if [[ -z "${CIVIFORM_VERSION}" ]]; then
   echo "CIVIFORM_VERSION needs to be set to version from https://github.com/civiform/civiform/releases"
   exit 1
 fi
+if [[ "${CIVIFORM_VERSION}" == 'latest' && "${CIVIFORM_MODE}" == 'prod' ]]; then
+  echo "Production deployments are required to specify a specific version from https://github.com/civiform/civiform/releases"
+  exit 1
+fi
 
 if [[ -z "${AWS_ACCESS_KEY_ID}" ]]; then
   export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
